spring.application.name=digital-queue-management
server.port=8080

spring.datasource.url=jdbc:h2:mem:queuedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.web.resources.cache.cachecontrol.no-cache=true

app.admin.username=yash
app.admin.password=yash1234

app.queue.max-size=50
